source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
platform :ios, '11.0'

target 'ApplozicAudioVideo_Example' do
  pod 'ApplozicAudioVideo', :path => '../'

  target 'ApplozicAudioVideo_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
