use_frameworks!

platform :ios, '9.0'

target 'ApplozicAudioVideo_Example' do
  pod 'ApplozicAudioVideo', :path => '../'

  target 'ApplozicAudioVideo_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
